// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocketsProof.Models;

#nullable disable

namespace SocketsProof.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocketsProof.Models.Client", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hostname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("OS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mac")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("LastSeen")
                        .HasDatabaseName("IX_Client_LastSeen");

                    b.HasIndex("mac")
                        .IsUnique()
                        .HasDatabaseName("IX_Client_Mac")
                        .HasFilter("[mac] IS NOT NULL");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("SocketsProof.Models.Command", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommandText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("SocketsProof.Models.CommandAck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AckedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CommandId")
                        .IsUnique();

                    b.ToTable("CommandAcks");
                });

            modelBuilder.Entity("SocketsProof.Models.DiskLog", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Iops")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double>("UsagePercent")
                        .HasColumnType("float");

                    b.Property<Guid>("clientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("freeMemory")
                        .HasColumnType("int");

                    b.Property<int>("totalMemory")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("clientId", "Timestamp")
                        .HasDatabaseName("IX_DiskLog_ClientId_Timestamp");

                    b.ToTable("DiskLog");
                });

            modelBuilder.Entity("SocketsProof.Models.Command", b =>
                {
                    b.HasOne("SocketsProof.Models.Client", "Node")
                        .WithMany("Commands")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("SocketsProof.Models.CommandAck", b =>
                {
                    b.HasOne("SocketsProof.Models.Command", "Command")
                        .WithOne("Ack")
                        .HasForeignKey("SocketsProof.Models.CommandAck", "CommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Command");
                });

            modelBuilder.Entity("SocketsProof.Models.DiskLog", b =>
                {
                    b.HasOne("SocketsProof.Models.Client", "Client")
                        .WithMany("diskLogs")
                        .HasForeignKey("clientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("SocketsProof.Models.Client", b =>
                {
                    b.Navigation("Commands");

                    b.Navigation("diskLogs");
                });

            modelBuilder.Entity("SocketsProof.Models.Command", b =>
                {
                    b.Navigation("Ack");
                });
#pragma warning restore 612, 618
        }
    }
}
